# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0006_auto_20160410_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprofiles',
            new_name='UserProfile',
        ),
    ]
