# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0007_auto_20160410_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contents_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follow_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follower_count',
            field=models.IntegerField(),
        ),
    ]
