# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0009_auto_20160410_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
